import type { Metadata } from "next";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Inter, Nunito_Sans } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { cn } from "@/lib/utils";
import Nav from "./(components)/Nav";

const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});
export const metadata: Metadata = {
  title: "Ticket App",
  description: "Generated by Kiraadaves",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${nunito.className} `}>
        <div className="flex flex-col h-screen max-h-screen">
          <Nav />
          <div className="flex-grow overflow-y-auto bg-[#fffff] text-[#FDC435]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
